check PR title

diff --git a/.github/workflows/pr-develop-branch.yml b/.github/workflows/pr-develop-branch.yml
--- a/.github/workflows/pr-develop-branch.yml
+++ b/.github/workflows/pr-develop-branch.yml
@@ -21,6 +21,18 @@ on:
 # Jobs to be executed when the above conditions are met
 jobs:
     # This is the name of the job. You can give it whatever name you want
+    check-pr-title:
+        name: Check PR title
+        runs-on: ubuntu-latest
+        steps:
+          - name: Validate PR Title
+            run: |
+              regex_pattern="^[A-Za-z]+-[0-9]+"
+              if [[ ! "${{ github.event.pull_request.title }}" =~ $regex_pattern ]]; then
+                echo "Invalid PR title format. Please follow the pattern: <prefix>-<number>"
+                exit 1
+              fi
+        
     check-commit-message:
         name: Check PR and Commit message
         runs-on: ubuntu-latest
